### ISSUE TITLE
Bug report: integrated_turn_position needs to be converted to degrees

### ISSUE THREAD

**Issue by daveraja** [segwayrmp/libsegwayrmp#1]
In segwayrmp.cpp line 574-575:

```
        _segway_status.integrated_turn_position    =
                                       getInt(packet.data[4], packet.data[5], packet.data[6], packet.data[7])/this->rev_to_counts;
```

I think needs to be converted to degrees rather than a ratio, something like:

```
        _segway_status.integrated_turn_position    =
                                      (getInt(packet.data[4], packet.data[5], packet.data[6], packet.data[7])/this->rev_to_counts)*360;
```

**Comment by wjwwood** [comment]
This was an oversight on my part, the datasheet gives the conversion from counts to revolutions, but I failed to add the additional conversion from revolutions to degrees which is the documented data type for my SegwayStatus object.  The new conversion has been added in commit 8f955dbed8903bfcbf3a which is also the v0.1-rc1 tag.
