### ISSUE TITLE
Object Library Compilation Failure

### ISSUE THREAD

**Issue by Roboman95** [segwayrmp/libsegwayrmp#16]
I'm currently working on implementing the libsegwayrmp library with vision processing logic using Code::Blocks as the IDE. I made a header file to interface with vision processing logic by using the example file of libsegwayrmp. After stabilizing the vision processing libraries, the only library issues I have left are the libraries of the libsegwayrmp. I linked the libsegwayrmp.a file to the project and compiled and got the compile error of:
 ||=== Build: Debug in SegwayBot (compiler: GNU GCC Compiler) ===|
/usr/local/libsegwayrmp/lib/libsegwayrmp.a(rmp_ftd2xx.cc.o)||In function `segwayrmp::FTD2XXRMPIO::disconnect()':|
/usr/local/libsegwayrmp/src/impl/rmp_ftd2xx.cc|251|undefined reference to`FT_Close'|
/usr/local/libsegwayrmp/src/impl/rmp_ftd2xx.cc|251|undefined reference to `FT_Close'|
/usr/local/libsegwayrmp/lib/libsegwayrmp.a(rmp_ftd2xx.cc.o)||In function`segwayrmp::FTD2XXRMPIO::connectBySerial()':|
/usr/local/libsegwayrmp/src/impl/rmp_ftd2xx.cc|312|undefined reference to `FT_OpenEx'|
/usr/local/libsegwayrmp/lib/libsegwayrmp.a(rmp_ftd2xx.cc.o)||In function`segwayrmp::FTD2XXRMPIO::connectByDescription()':|
/usr/local/libsegwayrmp/src/impl/rmp_ftd2xx.cc|339|undefined reference to `FT_OpenEx'|
/usr/local/libsegwayrmp/lib/libsegwayrmp.a(rmp_ftd2xx.cc.o)||In function`segwayrmp::FTD2XXRMPIO::connectByIndex()':|
/usr/local/libsegwayrmp/src/impl/rmp_ftd2xx.cc|364|undefined reference to `FT_Open'|
/usr/local/libsegwayrmp/lib/libsegwayrmp.a(rmp_ftd2xx.cc.o)||In function`segwayrmp::FTD2XXRMPIO::read(unsigned char_, int)':|
/usr/local/libsegwayrmp/src/impl/rmp_ftd2xx.cc|262|undefined reference to `FT_Read'|
/usr/local/libsegwayrmp/lib/libsegwayrmp.a(rmp_ftd2xx.cc.o)||In function`segwayrmp::FTD2XXRMPIO::write(unsigned char_, int)':|
/usr/local/libsegwayrmp/src/impl/rmp_ftd2xx.cc|279|undefined reference to `FT_Write'|
/usr/local/libsegwayrmp/lib/libsegwayrmp.a(rmp_ftd2xx.cc.o)||In function`segwayrmp::enumerateUSBDevices()':|
/usr/local/libsegwayrmp/src/impl/rmp_ftd2xx.cc|89|undefined reference to `FT_SetVIDPID'|
/usr/local/libsegwayrmp/src/impl/rmp_ftd2xx.cc|100|undefined reference to`FT_CreateDeviceInfoList'|
/usr/local/libsegwayrmp/src/impl/rmp_ftd2xx.cc|118|undefined reference to `FT_GetDeviceInfoList'|
/usr/local/libsegwayrmp/lib/libsegwayrmp.a(rmp_ftd2xx.cc.o)||In function`segwayrmp::FTD2XXRMPIO::connect()':|
/usr/local/libsegwayrmp/src/impl/rmp_ftd2xx.cc|191|undefined reference to `FT_SetBaudRate'|
/usr/local/libsegwayrmp/src/impl/rmp_ftd2xx.cc|203|undefined reference to`FT_SetTimeouts'|
/usr/local/libsegwayrmp/src/impl/rmp_ftd2xx.cc|214|undefined reference to `FT_SetLatencyTimer'|
/usr/local/libsegwayrmp/src/impl/rmp_ftd2xx.cc|225|undefined reference to`FT_SetFlowControl'|
/usr/local/libsegwayrmp/src/impl/rmp_ftd2xx.cc|236|undefined reference to `FT_Purge'|
||=== Build failed: 15 error(s), (0 minute(s), 0 second(s)) ===|

Then I linked the libftd2xx.a file to the project. Compile and got the error:
/usr/bin/ld: /usr/local/libsegwayrmp/lib/libftd2xx.a(ftd2xx.o)||undefined reference to symbol 'dlclose@@GLIBC_2.2.5'|

I don't think these set of errors are related both are  concerning for me.  Am I linking the libraries the wrong way?

**Comment by wjwwood** [comment]
Linking libftd2xx is the right thing to do to solve most of those errors. The remaining error you have is because you're not linking in `dl` with the option `-ldl`. This is done here:

https://github.com/segwayrmp/libsegwayrmp/blob/master/cmake/segwayrmp_ftd2xx.cmake#L19

Why aren't you using the CodeBlocks generator that cmake provides?

http://www.cmake.org/cmake/help/v3.0/generator/CodeBlocks.html

**Comment by Roboman95** [comment]
I added the -ldl to the dl and looks as such "dl -ldl" in the file. 

I'm sorry. I'm not familiar with cmake and the generators.

**Comment by wjwwood** [comment]
Well, I'm not familiar with CodeBlocks, so all I can tell you is that you need to link against `dl` to resolve the last issue you post:

```
/usr/bin/ld: /usr/local/libsegwayrmp/lib/libftd2xx.a(ftd2xx.o)||undefined reference to symbol 'dlclose@@GLIBC_2.2.5'|
```

I'd recommend you read up on cmake generators for CodeBlocks and add an option to the prescribed building instructions which allows it to generate CodeBlocks projects:

https://github.com/segwayrmp/libsegwayrmp/blob/master/Makefile#L12

**Comment by Roboman95** [comment]
The library file that resolves this error is called "libdl.so.2" for 32 bit. The file is located /usr/local/lib.
